# Generated by Django 4.2.5 on 2024-06-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="usertype",
            field=models.CharField(choices=[("Administrator", "Administrator"), ("BranchConvenor", "Branch Convenor"), ("User", "User")], default="Student", max_length=20),
        ),
    ]
