preference_form_fields = [
    "monday_early_breakfast",
    "monday_breakfast",
    "monday_tiffin_lunch",
    "monday_lunch",
    "monday_dinner",
    "tuesday_early_breakfast",
    "tuesday_breakfast",
    "tuesday_tiffin_lunch",
    "tuesday_lunch",
    "tuesday_dinner",
    "wednesday_early_breakfast",
    "wednesday_breakfast",
    "wednesday_tiffin_lunch",
    "wednesday_lunch",
    "wednesday_dinner",
    "thursday_early_breakfast",
    "thursday_breakfast",
    "thursday_tiffin_lunch",
    "thursday_lunch",
    "thursday_dinner",
    "friday_early_breakfast",
    "friday_breakfast",
    "friday_tiffin_lunch",
    "friday_lunch",
    "friday_dinner",
    "saturday_early_breakfast",
    "saturday_breakfast",
    "saturday_tiffin_lunch",
    "saturday_lunch",
    "saturday_dinner",
    "sunday_early_breakfast",
    "sunday_breakfast",
    "sunday_tiffin_lunch",
    "sunday_lunch",
    "sunday_dinner",
]
daywise_itemdata = {
    "monday_early_breakfast": {"day": "Monday", "mealtype": "EARLY_BREAKFAST"},
    "monday_breakfast": {"day": "Monday", "mealtype": "BREAKFAST"},
    "monday_tiffin_lunch": {"day": "Monday", "mealtype": "TIFFIN_LUNCH"},
    "monday_lunch": {"day": "Monday", "mealtype": "LUNCH"},
    "monday_dinner": {"day": "Monday", "mealtype": "DINNER"},
    "tuesday_early_breakfast": {"day": "Tuesday", "mealtype": "EARLY_BREAKFAST"},
    "tuesday_breakfast": {"day": "Tuesday", "mealtype": "BREAKFAST"},
    "tuesday_tiffin_lunch": {"day": "Tuesday", "mealtype": "TIFFIN_LUNCH"},
    "tuesday_lunch": {"day": "Tuesday", "mealtype": "LUNCH"},
    "tuesday_dinner": {"day": "Tuesday", "mealtype": "DINNER"},
    "wednesday_early_breakfast": {"day": "Wednesday", "mealtype": "EARLY_BREAKFAST"},
    "wednesday_breakfast": {"day": "Wednesday", "mealtype": "BREAKFAST"},
    "wednesday_tiffin_lunch": {"day": "Wednesday", "mealtype": "TIFFIN_LUNCH"},
    "wednesday_lunch": {"day": "Wednesday", "mealtype": "LUNCH"},
    "wednesday_dinner": {"day": "Wednesday", "mealtype": "DINNER"},
    "thursday_early_breakfast": {"day": "Thursday", "mealtype": "EARLY_BREAKFAST"},
    "thursday_breakfast": {"day": "Thursday", "mealtype": "BREAKFAST"},
    "thursday_tiffin_lunch": {"day": "Thursday", "mealtype": "TIFFIN_LUNCH"},
    "thursday_lunch": {"day": "Thursday", "mealtype": "LUNCH"},
    "thursday_dinner": {"day": "Thursday", "mealtype": "DINNER"},
    "friday_early_breakfast": {"day": "Friday", "mealtype": "EARLY_BREAKFAST"},
    "friday_breakfast": {"day": "Friday", "mealtype": "BREAKFAST"},
    "friday_tiffin_lunch": {"day": "Friday", "mealtype": "TIFFIN_LUNCH"},
    "friday_lunch": {"day": "Friday", "mealtype": "LUNCH"},
    "friday_dinner": {"day": "Friday", "mealtype": "DINNER"},
    "saturday_early_breakfast": {"day": "Saturday", "mealtype": "EARLY_BREAKFAST"},
    "saturday_breakfast": {"day": "Saturday", "mealtype": "BREAKFAST"},
    "saturday_tiffin_lunch": {"day": "Saturday", "mealtype": "TIFFIN_LUNCH"},
    "saturday_lunch": {"day": "Saturday", "mealtype": "LUNCH"},
    "saturday_dinner": {"day": "Saturday", "mealtype": "DINNER"},
    "sunday_early_breakfast": {"day": "Sunday", "mealtype": "EARLY_BREAKFAST"},
    "sunday_breakfast": {"day": "Sunday", "mealtype": "BREAKFAST"},
    "sunday_tiffin_lunch": {"day": "Sunday", "mealtype": "TIFFIN_LUNCH"},
    "sunday_lunch": {"day": "Sunday", "mealtype": "LUNCH"},
    "sunday_dinner": {"day": "Sunday", "mealtype": "DINNER"},
}
