# Generated by Django 4.2.9 on 2024-11-22 11:26

from django.db import migrations, models
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("address", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ItemMaster",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                (
                    "mealtype",
                    models.CharField(
                        choices=[("EARLY_BREAKFAST", "Early Break Fast"), ("BREAKFAST", "Break Fast"), ("LUNCH", "Lunch"), ("TIFFIN_LUNCH", "Tiffin Lunch"), ("DINNER", "Dinner")],
                        max_length=200,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="items/images/")),
                ("name", models.CharField(max_length=200)),
                ("item_code", models.CharField(blank=True, max_length=200, null=True)),
                ("price", models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                (
                    "available_days",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=200,
                    ),
                ),
                ("available_weeks", multiselectfield.db.fields.MultiSelectField(choices=[(1, "1st & 3rd Week"), (2, "2nd & 4th Week")], max_length=200)),
                ("is_veg", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Item Master",
                "verbose_name_plural": "Item Masters",
                "ordering": ("available_weeks", "available_days", "mealtype"),
            },
        ),
        migrations.CreateModel(
            name="MealCategory",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("order", models.PositiveIntegerField(default=1)),
                ("group", models.CharField(choices=[("ESSENTIAL", "Essential"), ("REGULAR", "Regular"), ("DELUXE", "Deluxe"), ("STANDARD", "Standard")], max_length=200)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=200)),
                ("image", models.ImageField(upload_to="mealcategories/image")),
                ("description", models.TextField(blank=True, null=True)),
                ("brochure", models.FileField(blank=True, null=True, upload_to="mealcategories/brochure/")),
            ],
            options={
                "verbose_name": "Meal Category",
                "verbose_name_plural": "Meal Categories",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="MealOrder",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("date", models.DateField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PREPERATION", "In Preparation"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=200,
                    ),
                ),
                ("is_donated", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Meal Order",
                "verbose_name_plural": "Meal Orders",
                "ordering": ("date",),
            },
        ),
        migrations.CreateModel(
            name="Preferance",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("session_id", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name": "Preferance",
                "verbose_name_plural": "Preferances",
                "ordering": ("user",),
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ("start_date",),
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=200)),
                (
                    "available_mealtypes",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[("EARLY_BREAKFAST", "Early Break Fast"), ("BREAKFAST", "Break Fast"), ("LUNCH", "Lunch"), ("TIFFIN_LUNCH", "Tiffin Lunch"), ("DINNER", "Dinner")],
                        max_length=200,
                    ),
                ),
                ("validity", models.IntegerField(choices=[(22, "22 Days"), (26, "26 Days"), (30, "30 Days")])),
                ("plan_price", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ("meal_category", "validity", "name"),
            },
        ),
        migrations.CreateModel(
            name="SubscriptionRequest",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("start_date", models.DateField(blank=True, null=True)),
                ("breakfast_address_room_no", models.CharField(blank=True, max_length=200, null=True)),
                ("breakfast_address_floor", models.CharField(blank=True, max_length=200, null=True)),
                ("breakfast_address_building_name", models.CharField(blank=True, max_length=200, null=True)),
                ("breakfast_address_street_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "breakfast_time",
                    models.CharField(
                        choices=[
                            ("0630:0700", "6:30AM to 7AM"),
                            ("0700:0730", "7AM to 7:30AM"),
                            ("0730:0800", "7:30AM to 8AM"),
                            ("0800:0830", "8AM to 8:30AM"),
                            ("0900:0930", "9AM to 9:30AM"),
                        ],
                        default="0900:0930",
                        max_length=200,
                        verbose_name="Delivery Time (Breakfast)",
                    ),
                ),
                ("breakfast_location", models.URLField(blank=True, null=True, verbose_name="Location Map Link")),
                ("lunch_address_room_no", models.CharField(blank=True, max_length=200, null=True)),
                ("lunch_address_floor", models.CharField(blank=True, max_length=200, null=True)),
                ("lunch_address_building_name", models.CharField(blank=True, max_length=200, null=True)),
                ("lunch_address_street_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "lunch_time",
                    models.CharField(
                        choices=[
                            ("1230:1300", "12:30PM to 1PM"),
                            ("1300:1330", "1PM to 1:30PM"),
                            ("1330:1400", "1:30PM to 2PM"),
                            ("1400:1430", "2PM to 2:30PM"),
                            ("1430:1500", "2:30PM to 3PM"),
                        ],
                        default="1230:1300",
                        max_length=200,
                        verbose_name="Delivery Time (Lunch",
                    ),
                ),
                ("lunch_location", models.URLField(blank=True, null=True, verbose_name="Location Map Link")),
                ("dinner_address_room_no", models.CharField(blank=True, max_length=200, null=True)),
                ("dinner_address_floor", models.CharField(blank=True, max_length=200, null=True)),
                ("dinner_address_building_name", models.CharField(blank=True, max_length=200, null=True)),
                ("dinner_address_street_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "dinner_time",
                    models.CharField(
                        choices=[
                            ("1930:2000", "7:30PM to 8PM"),
                            ("2000:2030", "8PM to 8:30PM"),
                            ("2030:2100", "8:30PM to 9PM"),
                            ("2100:2130", "9PM to 9:30PM"),
                            ("2130:2200", "9:30PM to 10PM"),
                        ],
                        default="2100:2130",
                        max_length=200,
                        verbose_name="Delivery Time (Dinner)",
                    ),
                ),
                ("dinner_location", models.URLField(blank=True, null=True, verbose_name="Location Map Link")),
                ("notes", models.TextField(blank=True, null=True)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], default="PENDING", max_length=200)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[("OBJECT_CREATED", "OBJECT_CREATED"), ("PLAN_SELECTED", "PLAN_SELECTED"), ("ADDRESS_ADDED", "ADDRESS_ADDED"), ("COMPLETED", "COMPLETED")],
                        default="OBJECT_CREATED",
                        max_length=200,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("meal_fee", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ("no_of_meals", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Subscription Request",
                "verbose_name_plural": "Subscription Requests",
                "ordering": ("start_date",),
            },
        ),
    ]
