# Generated by Django 4.2.9 on 2024-11-23 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionsubplan",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="subscriptionsubplan",
            name="plan",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.subscriptionplan"),
        ),
        migrations.AddField(
            model_name="subscriptionrequest",
            name="approved_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="approved_requests", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="subscriptionrequest",
            name="area",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="main.area", verbose_name="Zone"),
        ),
        migrations.AddField(
            model_name="subscriptionrequest",
            name="breakfast_address_area",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="breakfast_address_area", to="main.area"),
        ),
        migrations.AddField(
            model_name="subscriptionrequest",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrequest",
            name="delivery_staff",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"usertype": "Delivery"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrequest",
            name="dinner_address_area",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="dinner_address_area", to="main.area"),
        ),
        migrations.AddField(
            model_name="subscriptionrequest",
            name="lunch_address_area",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="lunch_address_area", to="main.area"),
        ),
        migrations.AddField(
            model_name="subscriptionrequest",
            name="plan",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="subscription_requests", to="main.subscriptionplan"),
        ),
        migrations.AddField(
            model_name="subscriptionrequest",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscription_requests", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="meal_category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.mealcategory"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscription_plan", to="main.subscriptionplan"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="request",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscription_requests", to="main.subscriptionrequest"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="preferance",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="preferance",
            name="friday_breakfast",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="friday_breakfast", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="friday_dinner",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="friday_dinner", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="friday_lunch",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="friday_lunch", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="monday_breakfast",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="monday_breakfast", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="monday_dinner",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="monday_dinner", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="monday_lunch",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="monday_lunch", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="saturday_breakfast",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="saturday_breakfast", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="saturday_dinner",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="saturday_dinner", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="saturday_lunch",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="saturday_lunch", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="sunday_breakfast",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sunday_breakfast", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="sunday_dinner",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sunday_dinner", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="sunday_lunch",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sunday_lunch", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="thursday_breakfast",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="thursday_breakfast", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="thursday_dinner",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="thursday_dinner", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="thursday_lunch",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="thursday_lunch", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="tuesday_breakfast",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="tuesday_breakfast", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="tuesday_dinner",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="tuesday_dinner", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="tuesday_lunch",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="tuesday_lunch", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="preferances", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="preferance",
            name="wednesday_breakfast",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="wednesday_breakfast", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="wednesday_dinner",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="wednesday_dinner", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preferance",
            name="wednesday_lunch",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="wednesday_lunch", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="meal_category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="main.mealcategory"),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="menu_items",
            field=models.ManyToManyField(related_name="meal_plans", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="mealorder",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="mealorder",
            name="item",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="itemmeals", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="mealorder",
            name="subscription",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="meals", to="main.subscription"),
        ),
        migrations.AddField(
            model_name="mealorder",
            name="subscription_plan",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mealsplan", to="main.subscriptionplan"),
        ),
        migrations.AddField(
            model_name="mealorder",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="usermeals", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="mealcategory",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="itemmaster",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="delivery_staffs",
            field=models.ManyToManyField(blank=True, limit_choices_to={"usertype": "Delivery"}, related_name="delivery_areas", to=settings.AUTH_USER_MODEL),
        ),
    ]
