# Generated by Django 4.2.9 on 2024-07-18 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="addresses", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="group",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="plans", to="main.plangroup"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to="main.subscriptionplan"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="plangroup",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="mealorder",
            name="combo",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="combomeals", to="main.combo"),
        ),
        migrations.AddField(
            model_name="mealorder",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="mealorder",
            name="subscription_plan",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mealsplan", to="main.subscriptionplan"),
        ),
        migrations.AddField(
            model_name="mealorder",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="usermeals", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="itemcategory",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="main.itemcategory"),
        ),
        migrations.AddField(
            model_name="item",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="combo",
            name="category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="combos", to="main.itemcategory"),
        ),
        migrations.AddField(
            model_name="combo",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="combo",
            name="items",
            field=models.ManyToManyField(related_name="combos", to="main.item"),
        ),
        migrations.AddField(
            model_name="branch",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useraddress",
            unique_together={("user", "is_default")},
        ),
    ]
