# Generated by Django 4.2.5 on 2024-06-19 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Asia Pacific", "Asia Pacific"),
                            ("Europe", "Europe"),
                            ("Middle East and Africa", "Middle East and Africa"),
                            ("North Asia", "North Asia"),
                            ("The Americas", "The Americas"),
                        ],
                        max_length=200,
                    ),
                ),
                ("city", models.CharField(max_length=200, verbose_name="City/Area")),
                ("airport_code", models.CharField(max_length=200)),
                ("ns24_level", models.CharField(blank=True, max_length=200, null=True, verbose_name="NS24 Level")),
                ("nw24_level", models.CharField(blank=True, max_length=200, null=True, verbose_name="NW24 Level")),
                ("ns25_level", models.CharField(blank=True, max_length=200, null=True, verbose_name="NS25 Level")),
                ("notes", models.TextField(blank=True, null=True)),
                ("country", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="airports", to="main.country")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Airport",
                "verbose_name_plural": "Airports",
                "ordering": ("city",),
            },
        ),
        migrations.CreateModel(
            name="Airline",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=200)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="airlines")),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Airline",
                "verbose_name_plural": "Airlines",
                "ordering": ("name",),
            },
        ),
    ]
