# Generated by Django 4.2.9 on 2024-11-27 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="friday_earlybreakfast",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="friday_earlybreakfast", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preference",
            name="friday_tiffinlunch",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="friday_tiffinlunch", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preference",
            name="monday_earlybreakfast",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="monday_earlybreakfast", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preference",
            name="monday_tiffinlunch",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="monday_tiffinlunch", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preference",
            name="saturday_earlybreakfast",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="saturday_earlybreakfast", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preference",
            name="saturday_tiffinlunch",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="saturday_tiffinlunch", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preference",
            name="sunday_earlybreakfast",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sunday_earlybreakfast", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preference",
            name="sunday_tiffinlunch",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sunday_tiffinlunch", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preference",
            name="thursday_earlybreakfast",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="thursday_earlybreakfast", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preference",
            name="thursday_tiffinlunch",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="thursday_tiffinlunch", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preference",
            name="tuesday_earlybreakfast",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="tuesday_earlybreakfast", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preference",
            name="tuesday_tiffinlunch",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="tuesday_tiffinlunch", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preference",
            name="wednesday_earlybreakfast",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="wednesday_earlybreakfast", to="main.itemmaster"),
        ),
        migrations.AddField(
            model_name="preference",
            name="wednesday_tiffinlunch",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="wednesday_tiffinlunch", to="main.itemmaster"),
        ),
    ]
