# Generated by Django 4.2.9 on 2024-11-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemmaster",
            name="group",
            field=models.CharField(choices=[("ESSENTIAL", "Essential"), ("REGULAR", "Regular"), ("DELUXE", "Deluxe"), ("STANDARD", "Standard")], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
