# Generated by Django 4.2.9 on 2024-11-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={"ordering": ("meal_category", "validity", "order"), "verbose_name": "Subscription Plan", "verbose_name_plural": "Subscription Plans"},
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="validity",
            field=models.PositiveIntegerField(choices=[(22, "22 Days"), (26, "26 Days"), (30, "30 Days")]),
        ),
    ]
