# Generated by Django 4.2.9 on 2024-11-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_itemmaster_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmaster",
            name="item_code",
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
