# Generated by Django 4.2.9 on 2024-11-27 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_preference_friday_earlybreakfast_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemmaster",
            name="meal_category",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="main.mealcategory"),
        ),
        migrations.AlterField(
            model_name="preference",
            name="friday_breakfast",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "BREAKFAST"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friday_breakfast",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="friday_dinner",
            field=models.ForeignKey(
                blank=True, limit_choices_to={"mealtype": "DINNER"}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="friday_dinner", to="main.itemmaster"
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="friday_earlybreakfast",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "EARLY_BREAKFAST"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friday_earlybreakfast",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="friday_lunch",
            field=models.ForeignKey(
                blank=True, limit_choices_to={"mealtype": "LUNCH"}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="friday_lunch", to="main.itemmaster"
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="friday_tiffinlunch",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "TIFFIN_LUNCH"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friday_tiffinlunch",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="monday_breakfast",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "BREAKFAST"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monday_breakfast",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="monday_dinner",
            field=models.ForeignKey(
                blank=True, limit_choices_to={"mealtype": "DINNER"}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="monday_dinner", to="main.itemmaster"
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="monday_earlybreakfast",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "EARLY_BREAKFAST"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monday_earlybreakfast",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="monday_lunch",
            field=models.ForeignKey(
                blank=True, limit_choices_to={"mealtype": "LUNCH"}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="monday_lunch", to="main.itemmaster"
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="monday_tiffinlunch",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "TIFFIN_LUNCH"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monday_tiffinlunch",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="saturday_breakfast",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "BREAKFAST"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saturday_breakfast",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="saturday_dinner",
            field=models.ForeignKey(
                blank=True, limit_choices_to={"mealtype": "DINNER"}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="saturday_dinner", to="main.itemmaster"
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="saturday_earlybreakfast",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "EARLY_BREAKFAST"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saturday_earlybreakfast",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="saturday_lunch",
            field=models.ForeignKey(
                blank=True, limit_choices_to={"mealtype": "LUNCH"}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="saturday_lunch", to="main.itemmaster"
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="saturday_tiffinlunch",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "TIFFIN_LUNCH"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saturday_tiffinlunch",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="sunday_breakfast",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "BREAKFAST"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sunday_breakfast",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="sunday_dinner",
            field=models.ForeignKey(
                blank=True, limit_choices_to={"mealtype": "DINNER"}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sunday_dinner", to="main.itemmaster"
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="sunday_earlybreakfast",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "EARLY_BREAKFAST"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sunday_earlybreakfast",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="sunday_lunch",
            field=models.ForeignKey(
                blank=True, limit_choices_to={"mealtype": "LUNCH"}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sunday_lunch", to="main.itemmaster"
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="sunday_tiffinlunch",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "TIFFIN_LUNCH"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sunday_tiffinlunch",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="thursday_breakfast",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "BREAKFAST"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thursday_breakfast",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="thursday_dinner",
            field=models.ForeignKey(
                blank=True, limit_choices_to={"mealtype": "DINNER"}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="thursday_dinner", to="main.itemmaster"
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="thursday_earlybreakfast",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "EARLY_BREAKFAST"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thursday_earlybreakfast",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="thursday_lunch",
            field=models.ForeignKey(
                blank=True, limit_choices_to={"mealtype": "LUNCH"}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="thursday_lunch", to="main.itemmaster"
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="thursday_tiffinlunch",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "TIFFIN_LUNCH"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thursday_tiffinlunch",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="tuesday_breakfast",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "BREAKFAST"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tuesday_breakfast",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="tuesday_dinner",
            field=models.ForeignKey(
                blank=True, limit_choices_to={"mealtype": "DINNER"}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="tuesday_dinner", to="main.itemmaster"
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="tuesday_earlybreakfast",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "EARLY_BREAKFAST"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tuesday_earlybreakfast",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="tuesday_lunch",
            field=models.ForeignKey(
                blank=True, limit_choices_to={"mealtype": "LUNCH"}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="tuesday_lunch", to="main.itemmaster"
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="tuesday_tiffinlunch",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "TIFFIN_LUNCH"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tuesday_tiffinlunch",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="wednesday_breakfast",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "BREAKFAST"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wednesday_breakfast",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="wednesday_dinner",
            field=models.ForeignKey(
                blank=True, limit_choices_to={"mealtype": "DINNER"}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="wednesday_dinner", to="main.itemmaster"
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="wednesday_earlybreakfast",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "EARLY_BREAKFAST"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wednesday_earlybreakfast",
                to="main.itemmaster",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="wednesday_lunch",
            field=models.ForeignKey(
                blank=True, limit_choices_to={"mealtype": "LUNCH"}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="wednesday_lunch", to="main.itemmaster"
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="wednesday_tiffinlunch",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"mealtype": "TIFFIN_LUNCH"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wednesday_tiffinlunch",
                to="main.itemmaster",
            ),
        ),
    ]
