# Generated by Django 4.2.9 on 2024-11-23 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0004_alter_itemmaster_item_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preference",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("session_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("friday_breakfast", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="friday_breakfast", to="main.itemmaster")),
                ("friday_dinner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="friday_dinner", to="main.itemmaster")),
                ("friday_lunch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="friday_lunch", to="main.itemmaster")),
                ("monday_breakfast", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="monday_breakfast", to="main.itemmaster")),
                ("monday_dinner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="monday_dinner", to="main.itemmaster")),
                ("monday_lunch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="monday_lunch", to="main.itemmaster")),
                (
                    "saturday_breakfast",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="saturday_breakfast", to="main.itemmaster"),
                ),
                ("saturday_dinner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="saturday_dinner", to="main.itemmaster")),
                ("saturday_lunch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="saturday_lunch", to="main.itemmaster")),
                ("sunday_breakfast", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sunday_breakfast", to="main.itemmaster")),
                ("sunday_dinner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sunday_dinner", to="main.itemmaster")),
                ("sunday_lunch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sunday_lunch", to="main.itemmaster")),
                (
                    "thursday_breakfast",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="thursday_breakfast", to="main.itemmaster"),
                ),
                ("thursday_dinner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="thursday_dinner", to="main.itemmaster")),
                ("thursday_lunch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="thursday_lunch", to="main.itemmaster")),
                (
                    "tuesday_breakfast",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="tuesday_breakfast", to="main.itemmaster"),
                ),
                ("tuesday_dinner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="tuesday_dinner", to="main.itemmaster")),
                ("tuesday_lunch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="tuesday_lunch", to="main.itemmaster")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="preferences", to=settings.AUTH_USER_MODEL)),
                (
                    "wednesday_breakfast",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="wednesday_breakfast", to="main.itemmaster"),
                ),
                ("wednesday_dinner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="wednesday_dinner", to="main.itemmaster")),
                ("wednesday_lunch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="wednesday_lunch", to="main.itemmaster")),
            ],
            options={
                "verbose_name": "Preference",
                "verbose_name_plural": "Preferences",
                "ordering": ("user",),
            },
        ),
        migrations.DeleteModel(
            name="Preferance",
        ),
    ]
