# Generated by Django 4.2.5 on 2024-06-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_combo_item_itemcategory_remove_airport_country_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="combo",
            options={"ordering": ("name",), "verbose_name": "Combo", "verbose_name_plural": "Combos"},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("name",), "verbose_name": "Item", "verbose_name_plural": "Items"},
        ),
        migrations.AlterModelOptions(
            name="itemcategory",
            options={"ordering": ("name",), "verbose_name": "Item Category", "verbose_name_plural": "Item Categories"},
        ),
        migrations.AlterField(
            model_name="combo",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
