# Generated by Django 4.2.9 on 2024-11-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_preference_delete_preferance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="name",
        ),
    ]
