# Generated by Django 4.2.5 on 2024-06-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_combo_options_alter_item_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="items/images/"),
        ),
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="items/images/"),
        ),
    ]
