# Generated by Django 4.2.9 on 2024-12-02 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0006_itemmaster_is_fallback_mealplan_is_fallback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="alternate_mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="preferred_language",
            field=models.CharField(blank=True, choices=[("en", "English"), ("ml", "Malayalam"), ("ar", "Arabic"), ("hi", "Hindi"), ("ta", "Tamil"), ("te", "Telugu")], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="subscription_subplan",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="preferences", to="main.subscriptionsubplan"),
        ),
        migrations.AddField(
            model_name="preference",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="mealplan",
            name="is_fallback",
            field=models.BooleanField(default=False, help_text="Day will be ignored for Fallback items (No Meal)"),
        ),
        migrations.CreateModel(
            name="DeliveryAddress",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("room_no", models.CharField(max_length=200)),
                ("floor", models.CharField(max_length=200)),
                ("building_name", models.CharField(max_length=200)),
                ("street_name", models.CharField(max_length=200)),
                ("location", models.URLField(blank=True, null=True, verbose_name="Location Map Link")),
                ("area", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="delivery_area", to="main.area")),
                ("creator", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL)),
                ("preferance", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="delivery_addresses", to="main.preference")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="delivery_addresses", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Delivery Address",
                "verbose_name_plural": "Delivery Addresses",
                "ordering": ("user",),
            },
        ),
        migrations.AddField(
            model_name="preference",
            name="breakfast_address",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="breakfast_address", to="main.deliveryaddress"),
        ),
        migrations.AddField(
            model_name="preference",
            name="dinner_address",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="dinner_address", to="main.deliveryaddress"),
        ),
        migrations.AddField(
            model_name="preference",
            name="early_breakfast_address",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="early_breakfast_address", to="main.deliveryaddress"),
        ),
        migrations.AddField(
            model_name="preference",
            name="lunch_address",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="lunch_address", to="main.deliveryaddress"),
        ),
        migrations.AddField(
            model_name="preference",
            name="tiffin_lunch_address",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="tiffin_lunch_address", to="main.deliveryaddress"),
        ),
    ]
