# Generated by Django 4.2.5 on 2024-06-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_combo_image_item_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="mealtype",
            field=models.CharField(choices=[("BREAKFAST", "Break Fast"), ("LUNCH", "Lunch"), ("DINNER", "Dinner")], default="LUNCH", max_length=200),
            preserve_default=False,
        ),
    ]
