# Generated by Django 4.2.5 on 2024-06-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_combo_mealtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="is_default",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="combo",
            name="price",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
