# Generated by Django 4.2.9 on 2024-12-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_preference_alternate_mobile_preference_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Subscription Starts from"),
        ),
        migrations.AddField(
            model_name="preference",
            name="status",
            field=models.CharField(choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], default="PENDING", max_length=200),
        ),
    ]
