# Generated by Django 4.2.9 on 2025-07-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_preference_completed_at_preference_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='address_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='contact_number',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Set as default delivery address'),
        ),
    ]
