# Generated by Django 4.2.5 on 2024-06-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_combo_is_default_alter_combo_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="week",
            field=models.CharField(choices=[(1, "ODD"), (2, "EVEN")], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
