# Generated by Django 4.2.9 on 2025-07-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_deliveryaddress_address_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='brand',
            field=models.CharField(default='mess for', max_length=200),
        ),
    ]
