# Generated by Django 4.2.9 on 2025-07-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_deliveryaddress_address_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryaddress',
            options={'ordering': ('preference',), 'verbose_name': 'Delivery Address', 'verbose_name_plural': 'Delivery Addresses'},
        ),
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='preferance',
            new_name='preference',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='user',
        ),
    ]
