# Generated by Django 4.2.5 on 2024-06-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_combo_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combo",
            name="week",
            field=models.CharField(choices=[(1, "1st & 3rd Week"), (2, "2nd & 4th Week")], max_length=200),
        ),
    ]
