# Generated by Django 4.2.5 on 2024-06-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_combo_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combo",
            name="week",
            field=models.PositiveIntegerField(choices=[(1, "1st & 3rd Week"), (2, "2nd & 4th Week")]),
        ),
    ]
