# Generated by Django 4.2.9 on 2025-07-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_deliveryaddress_options_and_more'),
        ('main', '0010_preference_brand'),
    ]

    operations = [
    ]
