# Generated by Django 4.2.9 on 2025-07-18 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_merge_20250718_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='preference',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='delivery_staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'usertype': 'Delivery'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preference',
            name='meal_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='preference',
            name='no_of_meals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='preference',
            name='brand',
            field=models.CharField(default='Mess for', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='main.preference'),
        ),
        migrations.DeleteModel(
            name='SubscriptionRequest',
        ),
    ]
