# Generated by Django 4.2.5 on 2024-06-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_combo_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="available_on",
            field=models.CharField(
                choices=[
                    ("Sunday", "Sunday"),
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                ],
                default="Monday",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
