# Generated by Django 4.2.9 on 2025-07-18 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_remove_subscription_user_preference_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermeals', to=settings.AUTH_USER_MODEL),
        ),
    ]
