# Generated by Django 4.2.5 on 2024-06-19 10:16

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_combo_available_on"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="combo",
            options={"ordering": ("week", "available_on", "mealtype"), "verbose_name": "Combo", "verbose_name_plural": "Combos"},
        ),
        migrations.AddField(
            model_name="item",
            name="available_on",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="combo",
            name="available_on",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                max_length=200,
            ),
        ),
    ]
