# Generated by Django 4.2.5 on 2024-06-19 11:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0013_alter_combo_options_item_available_on_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="District",
            new_name="SubscriptionPlan",
        ),
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={"ordering": ("name",), "verbose_name": "Subscription Plan", "verbose_name_plural": "Subscription Plans"},
        ),
    ]
