# Generated by Django 4.2.5 on 2024-06-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_rename_district_subscriptionplan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="plantype",
            field=models.CharField(choices=[(5, "5 Days"), (6, "6 Days"), (7, "7 Days"), (22, "22 Days"), (26, "26 Days"), (30, "30 Days")], default=5, max_length=200),
            preserve_default=False,
        ),
    ]
