# Generated by Django 4.2.5 on 2024-06-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_subscriptionplan_plantype"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="bimonthly_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="first_order_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="monthly_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="regular_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
